version: "3.3"

services:
  site:
    build: ./dummy-site

  hypothesis_pdfjs:
    build: ./hypothesis-pdfjs

  hypothesis_client:
    build: 
      context: ./hypothesis-client
      dockerfile: Dockerfile
      args:
        SIDEBAR_APP_URL: ${SIDEBAR_APP_URL}
        CLIENT_ID: ${CLIENT_ID}        

  nginx:
    image: nginx:latest
    depends_on:
      - site
      - hypothesis_client
      - hypothesis_pdfjs
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.stage.conf:/etc/nginx/nginx.conf              