version: "3.3"

services:
  hypothesis_client:
    build: ./hypothesis-client
    command: make dev
    volumes:
      - ./hypothesis-client:/usr/src/app      

  hypothesis_h: 
    build: ./hypothesis-h
    command: bash -c "./scripts/await-elastic.sh && make dev"
    depends_on:
      - postgres
      - elasticsearch
      - rabbit
    environment:
      CLIENT_OAUTH_ID: ${CLIENT_ID}  
      CLIENT_URL: ${SIDEBAR_APP_URL}
    volumes:
      - ./hypothesis-h:/usr/src/app/

  postgres:
    image: postgres:11.5-alpine   
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 1s

  elasticsearch:
    image: hypothesis/elasticsearch:latest
    environment:
      - discovery.type=single-node

  rabbit:
    image: rabbitmq:3.6-management-alpine

  nginx:
    image: nginx:latest
    depends_on:
      - hypothesis_client
      - hypothesis_h
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf                    